/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lzb_record_effect_EffectUtils */

#ifndef _Included_com_lzb_record_effect_EffectUtils
#define _Included_com_lzb_record_effect_EffectUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef com_lzb_record_effect_EffectUtils_MODE_NORMAL
#define com_lzb_record_effect_EffectUtils_MODE_NORMAL 0L
#undef com_lzb_record_effect_EffectUtils_MODE_LUOLI
#define com_lzb_record_effect_EffectUtils_MODE_LUOLI 1L
#undef com_lzb_record_effect_EffectUtils_MODE_DASHU
#define com_lzb_record_effect_EffectUtils_MODE_DASHU 2L
#undef com_lzb_record_effect_EffectUtils_MODE_JINGSONG
#define com_lzb_record_effect_EffectUtils_MODE_JINGSONG 3L
#undef com_lzb_record_effect_EffectUtils_MODE_GAOGUAI
#define com_lzb_record_effect_EffectUtils_MODE_GAOGUAI 4L
#undef com_lzb_record_effect_EffectUtils_MODE_KONGLING
#define com_lzb_record_effect_EffectUtils_MODE_KONGLING 5L
#undef com_lzb_record_effect_EffectUtils_MODE_HECHANG
#define com_lzb_record_effect_EffectUtils_MODE_HECHANG 6L
/*
 * Class:     com_lzb_record_effect_EffectUtils
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_lzb_record_effect_EffectUtils_fix
        (JNIEnv *, jclass, jstring, jint, jint);

JNIEXPORT void JNICALL Java_com_lzb_record_effect_EffectUtils_stop
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_lzb_record_effect_EffectUtils_downVolume
        (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT void JNICALL Java_com_lzb_record_effect_EffectUtils_fasterPCM
        (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT void JNICALL Java_com_lzb_record_effect_EffectUtils_slowerPCM
        (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT void JNICALL Java_com_lzb_record_effect_EffectUtils_slowerPCMRealTime
        (JNIEnv *, jobject , jbyteArray);
#ifdef __cplusplus
}
#endif
#endif
